name: Publish
on:
    push:
        branches:
            - master
    workflow_dispatch:
jobs:
    build-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
            - name: Install
              run: npm ci
            - name: Build
              run: npm run build
            - name: Build docs
              run: npm run docs
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.6.8
              with:
                  branch: gh-pages
                  folder: docs
                  single-commit: true
